In [1]:
import pandas as pd
import Go_tools
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
transcriptome = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/plate1_5_tpm_normalized.csv",
    index_col=0,
)
rows_to_drop_expression_data = [
    "A2450525897_n01_undetermined",
    "A2449446903_n01_undetermined",
    "B250508004_n01_undetermined",
    "B2449500127_n01_undetermined",
]
transcriptome = transcriptome.drop(index=rows_to_drop_expression_data)
transcriptome = transcriptome.sort_index()
metadata = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/Plates_1_to_5_metadata_merged_luke.csv",
    index_col=0,
)
metadata = metadata.drop(
    columns=[
        "arb.sort",
        "sample-id",
        "Ambiguous Unstranded",
        "Ambiguous Forward",
        "Multimapping",
        "Unmapped Over Mapped",
    ]
)
metadata["Date and Time"] = metadata["date"] + " " + metadata["time"]
luke_time_data_format = "%-m/%-d/%y %-H:%-M"
metadata["Date and Time"] = pd.to_datetime(
    metadata["Date and Time"], format=luke_time_data_format
)
unusable_samples = [
    "A2450525897_n01_LICRNA01_A06",
    "A2450525897_n01_LICRNA01_A08",
    "A2450525897_n01_LICRNA01_C11",
    "A2450525897_n01_LICRNA01_D11",
    "A2450525897_n01_LICRNA01_D12",
    "A2449446903_n01_LICRNA02_F01",
    "B2449500127_n01_LICRNA04_A04",
    "B2449500127_n01_LICRNA04_A06",
    "B2449500127_n01_LICRNA04_A07",
]
borderline_unusable = [
    "A2450525897_n01_LICRNA01_F03",
    "A2450525897_n01_LICRNA01_G07",
    "A2449446903_n01_LICRNA02_A04",
    "A2449446903_n01_LICRNA02_H10",
    "B2449500127_n01_LICRNA04_H02",
    "B2449500127_n01_LICRNA04_H11",
]
all_unsable = borderline_unusable + unusable_samples
# trimmed_transcriptome = transcriptome.drop(index=all_unsable)
# trimmed_metadata = metadata.drop(index=all_unsable)
## Get plate 5 samples and remove what they replaced from the metadata to avoid duplicates
plate_5_replacements = metadata.loc[metadata["rnaprepplate"] == "LICRNA_05"]
non_plate_5_samples = metadata.loc[metadata["rnaprepplate"] != "LICRNA_05"]
replaced_samples = non_plate_5_samples.loc[
    non_plate_5_samples["sampID"].isin(plate_5_replacements["sampID"])
]
trimmed_metadata = metadata.drop(index=replaced_samples.index)
### get duplicates and drop the one with higher total genes, so that we can drop everything from the main list
double_duplicates = (
    trimmed_metadata.loc[
        trimmed_metadata.duplicated(
            subset="sampID",
            keep=False,
        )
    ]
    .sort_values(by="Total Reads")
    .drop_duplicates(subset="sampID", keep="first")
)
trimmed_metadata = trimmed_metadata.drop(index=double_duplicates.index)
trimmed_metadata
trimmed_transcriptome = transcriptome.loc[trimmed_metadata.index]
trimmed_transcriptome

,AT1G01010,AT1G01020,AT1G03987,AT1G01030,AT1G01040,AT1G03993,AT1G01046,AT1G01050,AT1G03997,AT1G01060,...,ArthCt124,ArthCr088,ArthCt112,ArthCp088,ArthCp086,ArthCt118,ArthCp083,ArthCt111,ArthCp084,ArthCp085
filename,,,,,,,,,,,,,,,,,,,,,
A2450525897_n01_LICRNA01_A01,4.944011,1.397952,0.0,5.994827,5.876072,0.0,0.0,58.062147,0.0,15.150509,...,0.000000,13.256631,0.000000,0.938539,0.0,0.0,0.956942,0.0,0.000000,1.597223
A2450525897_n01_LICRNA01_B01,2.911492,4.379655,0.0,2.665837,3.261267,0.0,0.0,57.934612,0.0,10.439273,...,0.000000,13.734068,0.000000,0.350043,0.0,0.0,0.166556,0.0,0.000000,2.184266
A2450525897_n01_LICRNA01_C01,6.270921,9.657724,0.0,0.000000,4.158376,0.0,0.0,38.161651,0.0,10.623477,...,34.304262,31.001035,0.000000,0.000000,0.0,0.0,0.051248,0.0,0.000000,0.855379
A2450525897_n01_LICRNA01_E01,3.690795,5.635420,0.0,3.786748,2.141076,0.0,0.0,37.996762,0.0,8.530523,...,0.000000,9.676399,0.000000,0.000000,0.0,0.0,0.142875,0.0,0.000000,1.987260
A2450525897_n01_LICRNA01_F01,2.781737,8.695001,0.0,2.016710,8.565957,0.0,0.0,64.854957,0.0,16.845214,...,0.000000,67.280011,0.000000,0.000000,0.0,0.0,0.496000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A2534491401_n01_LICRNA05_D12,0.000000,8.339930,0.0,7.860235,3.199519,0.0,0.0,39.201659,0.0,1.057777,...,0.000000,4.602930,22.529946,1.333133,0.0,0.0,0.036247,0.0,4.867353,5.293749
A2534491401_n01_LICRNA05_E12,0.000000,1.692107,0.0,1.577446,3.055581,0.0,0.0,29.564231,0.0,12.872063,...,0.000000,6.899039,1.605254,3.951394,0.0,0.0,0.839348,0.0,0.000000,3.222183
A2534491401_n01_LICRNA05_F12,0.641335,5.972190,0.0,1.641699,5.632121,0.0,0.0,48.940407,0.0,24.612749,...,0.000000,7.502750,0.000000,1.799150,0.0,0.0,0.000000,0.0,0.000000,0.145801
A2534491401_n01_LICRNA05_G12,1.727665,9.030810,0.0,1.779114,5.008559,0.0,0.0,40.864049,0.0,24.606427,...,0.000000,4.863406,0.000000,4.041995,0.0,0.0,0.103031,0.0,0.000000,3.821523
A2534491401_n01_LICRNA05_H12,0.728373,8.660978,0.0,4.130582,3.850938,0.0,0.0,39.892585,0.0,27.409934,...,6.830520,2.143986,13.661041,4.553680,0.0,0.0,0.392867,0.0,0.000000,4.669592

In [3]:
circadian_results_1 = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/Output_for_Luke/Gene_cosine_results_circadian_experiment_1.csv"
)

circadian_results_2 = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/Output_for_Luke/Gene_cosine_results_circadian_experiment_2.csv"
)

In [4]:
circadian_results_1

,test,period,p,q,amplitude,p(amplitude),q(amplitude),CI(amplitude),acrophase,p(acrophase),q(acrophase),CI(acrophase),acrophase[h]
0,AT1G01020,24.0,2.102497e-02,5.078886e-02,0.918085,4.710387e-03,1.136635e-02,"[np.float64(0.2813949244319637), np.float64(1....",-1.169566,1.142287e-03,3.312285e-03,"[np.float64(-1.8742590565617578), np.float64(-...",4.467411
1,AT1G01030,24.0,1.022071e-01,1.755511e-01,0.386880,3.113175e-02,5.341614e-02,"[np.float64(0.03507695668373073), np.float64(0...",-2.801896,1.101758e-09,7.607475e-09,"[np.float64(-3.703057726194051), np.float64(-1...",10.702452
2,AT1G01040,24.0,2.707276e-01,3.724769e-01,0.316121,1.038610e-01,1.429474e-01,"[np.float64(-0.06483027596836577), np.float64(...",-0.646499,3.203545e-01,4.398152e-01,"[np.float64(-1.921608941659519), np.float64(0....",2.469444
3,AT1G01050,24.0,5.989641e-01,6.764105e-01,1.435231,3.101725e-01,3.503685e-01,"[np.float64(-1.336579953849928), np.float64(4....",0.946954,3.089308e-01,4.279015e-01,"[np.float64(-0.8771777739292927), np.float64(2...",20.382901
4,AT1G01060,24.0,1.079806e-22,3.717545e-20,10.427311,1.313264e-38,4.521291e-36,"[np.float64(8.854566775117929), np.float64(12....",3.130199,0.000000e+00,0.000000e+00,"[np.float64(2.974739132189778), np.float64(3.2...",12.043522
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14799,ArthCt114,24.0,2.785747e-01,3.807256e-01,2.233417,1.078156e-01,1.473914e-01,"[np.float64(-0.4887055638127329), np.float64(4...",0.853307,1.475623e-01,2.381199e-01,"[np.float64(-0.30154453761883393), np.float64(...",20.740606
14800,ArthCt124,24.0,4.074518e-01,5.051010e-01,1.043644,1.787614e-01,2.216402e-01,"[np.float64(-0.47765425885048907), np.float64(...",3.010746,1.023445e-04,3.622062e-04,"[np.float64(1.4918254456525386), np.float64(4....",12.499797
14801,ArthCr088,24.0,5.301851e-01,6.166125e-01,0.384770,2.593235e-01,3.015494e-01,"[np.float64(-0.2837949765125131), np.float64(1...",-2.883700,1.148742e-03,3.326027e-03,"[np.float64(-4.622059771966897), np.float64(-1...",11.014923
14802,ArthCp088,24.0,9.359798e-02,1.641930e-01,0.981437,2.798974e-02,4.904831e-02,"[np.float64(0.10605937085861394), np.float64(1...",-2.926267,1.598744e-10,1.194741e-09,"[np.float64(-3.8230310076464984), np.float64(-...",11.177518
14803,ArthCp085,24.0,8.274965e-01,8.638500e-01,0.199468,5.379446e-01,5.616172e-01,"[np.float64(-0.43526984454730633), np.float64(...",-0.578823,7.365235e-01,8.156623e-01,"[np.float64(-3.9506074419551784), np.float64(2...",2.210942

In [5]:
circadian_results_2

,test,period,p,q,amplitude,p(amplitude),q(amplitude),CI(amplitude),acrophase,p(acrophase),q(acrophase),CI(acrophase),acrophase[h]
0,AT1G01020,24.0,1.617731e-01,3.148832e-01,0.787583,5.441679e-02,1.059196e-01,"[np.float64(-0.014928620348517274), np.float64...",-2.741807,5.234006e-07,3.269891e-06,"[np.float64(-3.8128205048213832), np.float64(-...",10.472931
1,AT1G01030,24.0,1.379443e-01,2.854384e-01,1.131356,4.479593e-02,9.256282e-02,"[np.float64(0.02627531243565806), np.float64(2...",-1.081014,2.399089e-02,4.833099e-02,"[np.float64(-2.019645085874023), np.float64(-0...",4.129169
2,AT1G01040,24.0,2.864689e-01,4.506485e-01,0.290109,1.124734e-01,1.767790e-01,"[np.float64(-0.0681400198728), np.float64(0.64...",-2.249126,2.896831e-04,1.022486e-03,"[np.float64(-3.4653997213102965), np.float64(-...",8.591030
3,AT1G01050,24.0,1.724911e-02,7.484175e-02,7.740440,3.641136e-03,1.584356e-02,"[np.float64(2.5228947282096685), np.float64(12...",-1.633746,3.398830e-07,2.184052e-06,"[np.float64(-2.2616214872443208), np.float64(-...",6.240451
4,AT1G01060,24.0,9.607864e-16,4.190775e-13,6.437807,2.438295e-23,1.063540e-20,"[np.float64(5.170106632863515), np.float64(7.7...",-2.765351,1.903328e-150,1.141521e-147,"[np.float64(-2.972815722700038), np.float64(-2...",10.562862
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14389,ArthCr090,24.0,2.368318e-01,3.996433e-01,4.200396,8.755998e-02,1.479444e-01,"[np.float64(-0.6184805402817144), np.float64(9...",0.256973,6.799672e-01,7.612544e-01,"[np.float64(-0.9639936892917647), np.float64(1...",23.018434
14390,ArthCr089,24.0,9.036854e-02,2.200956e-01,13.244519,2.650738e-02,6.467999e-02,"[np.float64(1.5445048243626562), np.float64(24...",0.117478,8.079051e-01,8.628764e-01,"[np.float64(-0.8295602070891722), np.float64(1...",23.551266
14391,ArthCr088,24.0,1.125260e-02,5.650884e-02,2.913385,2.196355e-03,1.106388e-02,"[np.float64(1.0487374623217105), np.float64(4....",-0.200791,5.648156e-01,6.602205e-01,"[np.float64(-0.8843770270100055), np.float64(0...",0.766965
14392,ArthCp088,24.0,4.657019e-01,6.075144e-01,0.565033,2.148337e-01,2.803296e-01,"[np.float64(-0.32779139153230186), np.float64(...",0.224890,7.936695e-01,8.518439e-01,"[np.float64(-1.4603682464964347), np.float64(1...",23.140982
14393,ArthCp085,24.0,4.989909e-01,6.344382e-01,1.020763,2.370602e-01,3.015416e-01,"[np.float64(-0.6713168200133985), np.float64(2...",0.274890,7.597618e-01,8.244509e-01,"[np.float64(-1.4869986102504784), np.float64(2...",22.949998

In [6]:
common_genes = set(circadian_results_1["test"]).intersection(
    set(circadian_results_2["test"])
)
filtered_circadian_1 = circadian_results_1[
    circadian_results_1["test"].isin(common_genes)
]
filtered_circadian_2 = circadian_results_2[
    circadian_results_2["test"].isin(common_genes)
]

background_genes = set(circadian_results_1["test"]).union(
    set(circadian_results_2["test"])
)

In [7]:
print(len(common_genes))
print(len(circadian_results_1["test"].unique()))
print(len(circadian_results_2["test"].unique()))

14187
14804
14394

In [8]:
trimmed_transcriptome

,AT1G01010,AT1G01020,AT1G03987,AT1G01030,AT1G01040,AT1G03993,AT1G01046,AT1G01050,AT1G03997,AT1G01060,...,ArthCt124,ArthCr088,ArthCt112,ArthCp088,ArthCp086,ArthCt118,ArthCp083,ArthCt111,ArthCp084,ArthCp085
filename,,,,,,,,,,,,,,,,,,,,,
A2450525897_n01_LICRNA01_A01,4.944011,1.397952,0.0,5.994827,5.876072,0.0,0.0,58.062147,0.0,15.150509,...,0.000000,13.256631,0.000000,0.938539,0.0,0.0,0.956942,0.0,0.000000,1.597223
A2450525897_n01_LICRNA01_B01,2.911492,4.379655,0.0,2.665837,3.261267,0.0,0.0,57.934612,0.0,10.439273,...,0.000000,13.734068,0.000000,0.350043,0.0,0.0,0.166556,0.0,0.000000,2.184266
A2450525897_n01_LICRNA01_C01,6.270921,9.657724,0.0,0.000000,4.158376,0.0,0.0,38.161651,0.0,10.623477,...,34.304262,31.001035,0.000000,0.000000,0.0,0.0,0.051248,0.0,0.000000,0.855379
A2450525897_n01_LICRNA01_E01,3.690795,5.635420,0.0,3.786748,2.141076,0.0,0.0,37.996762,0.0,8.530523,...,0.000000,9.676399,0.000000,0.000000,0.0,0.0,0.142875,0.0,0.000000,1.987260
A2450525897_n01_LICRNA01_F01,2.781737,8.695001,0.0,2.016710,8.565957,0.0,0.0,64.854957,0.0,16.845214,...,0.000000,67.280011,0.000000,0.000000,0.0,0.0,0.496000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A2534491401_n01_LICRNA05_D12,0.000000,8.339930,0.0,7.860235,3.199519,0.0,0.0,39.201659,0.0,1.057777,...,0.000000,4.602930,22.529946,1.333133,0.0,0.0,0.036247,0.0,4.867353,5.293749
A2534491401_n01_LICRNA05_E12,0.000000,1.692107,0.0,1.577446,3.055581,0.0,0.0,29.564231,0.0,12.872063,...,0.000000,6.899039,1.605254,3.951394,0.0,0.0,0.839348,0.0,0.000000,3.222183
A2534491401_n01_LICRNA05_F12,0.641335,5.972190,0.0,1.641699,5.632121,0.0,0.0,48.940407,0.0,24.612749,...,0.000000,7.502750,0.000000,1.799150,0.0,0.0,0.000000,0.0,0.000000,0.145801
A2534491401_n01_LICRNA05_G12,1.727665,9.030810,0.0,1.779114,5.008559,0.0,0.0,40.864049,0.0,24.606427,...,0.000000,4.863406,0.000000,4.041995,0.0,0.0,0.103031,0.0,0.000000,3.821523
A2534491401_n01_LICRNA05_H12,0.728373,8.660978,0.0,4.130582,3.850938,0.0,0.0,39.892585,0.0,27.409934,...,6.830520,2.143986,13.661041,4.553680,0.0,0.0,0.392867,0.0,0.000000,4.669592

In [9]:
circadian_metadata = trimmed_metadata.loc[
    trimmed_metadata["Experiment Type"].str.contains("Circadian")
]
circadian_transcriptome = trimmed_transcriptome.loc[
    trimmed_metadata["Experiment Type"].str.contains("Circadian")
]

In [15]:
trimmed_circadian_transcriptome = circadian_transcriptome.loc[
    :, (circadian_transcriptome > 1).sum() > 150
]
extra_clean_gene_list = trimmed_circadian_transcriptome.columns.to_list()
extra_clean_gene_list

['AT1G01020',
 'AT1G01040',
 'AT1G01050',
 'AT1G01060',
 'AT1G01080',
 'AT1G01090',
 'AT1G01100',
 'AT1G01120',
 'AT1G01130',
 'AT1G01140',
 'AT1G01160',
 'AT1G01170',
 'AT1G01180',
 'AT1G01210',
 'AT1G01220',
 'AT1G01230',
 'AT1G01240',
 'AT1G01250',
 'AT1G01260',
 'AT1G01290',
 'AT1G01300',
 'AT1G01320',
 'AT1G01350',
 'AT1G01360',
 'AT1G01380',
 'AT1G01420',
 'AT1G01430',
 'AT1G01470',
 'AT1G01490',
 'AT1G01500',
 'AT1G01510',
 'AT1G01540',
 'AT1G01550',
 'AT1G01600',
 'AT1G01610',
 'AT1G01620',
 'AT1G01630',
 'AT1G01650',
 'AT1G01710',
 'AT1G01720',
 'AT1G01725',
 'AT1G01730',
 'AT1G01780',
 'AT1G01790',
 'AT1G01800',
 'AT1G01820',
 'AT1G01830',
 'AT1G01860',
 'AT1G01900',
 'AT1G01910',
 'AT1G01940',
 'AT1G01950',
 'AT1G01960',
 'AT1G01970',
 'AT1G01990',
 'AT1G02000',
 'AT1G02065',
 'AT1G02080',
 'AT1G02090',
 'AT1G02100',
 'AT1G02110',
 'AT1G02120',
 'AT1G02130',
 'AT1G02140',
 'AT1G02145',
 'AT1G02150',
 'AT1G02160',
 'AT1G02170',
 'AT1G02180',
 'AT1G02205',
 'AT1G02260',
 'AT1G02270',
 'AT1G02280',
 'AT1G02300',
 'AT1G02305',
 'AT1G02330',
 'AT1G02335',
 'AT1G02350',
 'AT1G04107',
 'AT1G02360',
 'AT1G02410',
 'AT1G02475',
 'AT1G02500',
 'AT1G02560',
 'AT1G02610',
 'AT1G02660',
 'AT1G02680',
 'AT1G02705',
 'AT1G02730',
 'AT1G02740',
 'AT1G02750',
 'AT1G02780',
 'AT1G02816',
 'AT1G02820',
 'AT1G02840',
 'AT1G02860',
 'AT1G02870',
 'AT1G02880',
 'AT1G02890',
 'AT1G02900',
 'AT1G02910',
 'AT1G02920',
 'AT1G02930',
 'AT1G02960',
 'AT1G03030',
 'AT1G03040',
 'AT1G03060',
 'AT1G03080',
 'AT1G03106',
 'AT1G03110',
 'AT1G03130',
 'AT1G03140',
 'AT1G03150',
 'AT1G03160',
 'AT1G03210',
 'AT1G03220',
 'AT1G03250',
 'AT1G03260',
 'AT1G03280',
 'AT1G03290',
 'AT1G03310',
 'AT1G03330',
 'AT1G03350',
 'AT1G03360',
 'AT1G03365',
 'AT1G03370',
 'AT1G03380',
 'AT1G03400',
 'AT1G03430',
 'AT1G03440',
 'AT1G03475',
 'AT1G04193',
 'AT1G04197',
 'AT1G03520',
 'AT1G03530',
 'AT1G03590',
 'AT1G03600',
 'AT1G03610',
 'AT1G03630',
 'AT1G03650',
 'AT1G03680',
 'AT1G03730',
 'AT1G03740',
 'AT1G03750',
 'AT1G03820',
 'AT1G03850',
 'AT1G03860',
 'AT1G03870',
 'AT1G03900',
 'AT1G03905',
 'AT1G03910',
 'AT1G03930',
 'AT1G04217',
 'AT1G03935',
 'AT1G03950',
 'AT1G03970',
 'AT1G04000',
 'AT1G04040',
 'AT1G04070',
 'AT1G04080',
 'AT1G04120',
 'AT1G04140',
 'AT1G04170',
 'AT1G04190',
 'AT1G04200',
 'AT1G04220',
 'AT1G04240',
 'AT1G04250',
 'AT1G04260',
 'AT1G04270',
 'AT1G04280',
 'AT1G04290',
 'AT1G04295',
 'AT1G04300',
 'AT1G04340',
 'AT1G04350',
 'AT1G04400',
 'AT1G04410',
 'AT1G04420',
 'AT1G04425',
 'AT1G04430',
 'AT1G04440',
 'AT1G04263',
 'AT1G04480',
 'AT1G04510',
 'AT1G04520',
 'AT1G04530',
 'AT1G04550',
 'AT1G04555',
 'AT1G04620',
 'AT1G04630',
 'AT1G04635',
 'AT1G04640',
 'AT1G04680',
 'AT1G04690',
 'AT1G04710',
 'AT1G04750',
 'AT1G04770',
 'AT1G04780',
 'AT1G04790',
 'AT1G04800',
 'AT1G04810',
 'AT1G04820',
 'AT1G04830',
 'AT1G04850',
 'AT1G04860',
 'AT1G04870',
 'AT1G04910',
 'AT1G04940',
 'AT1G04950',
 'AT1G04960',
 'AT1G04970',
 'AT1G04980',
 'AT1G04985',
 'AT1G04990',
 'AT1G05010',
 'AT1G05060',
 'AT1G05070',
 'AT1G05120',
 'AT1G05135',
 'AT1G05140',
 'AT1G05150',
 'AT1G05160',
 'AT1G05170',
 'AT1G05180',
 'AT1G05190',
 'AT1G05205',
 'AT1G05210',
 'AT1G05230',
 'AT1G05270',
 'AT1G05300',
 'AT1G05340',
 'AT1G05350',
 'AT1G05380',
 'AT1G05385',
 'AT1G05410',
 'AT1G05430',
 'AT1G05460',
 'AT1G05500',
 'AT1G05520',
 'AT1G05560',
 'AT1G05570',
 'AT1G05575',
 'AT1G05590',
 'AT1G05600',
 'AT1G05620',
 'AT1G05720',
 'AT1G05780',
 'AT1G05785',
 'AT1G05790',
 'AT1G05805',
 'AT1G05810',
 'AT1G05835',
 'AT1G05840',
 'AT1G05850',
 'AT1G05870',
 'AT1G05890',
 'AT1G05900',
 'AT1G05940',
 'AT1G05960',
 'AT1G05970',
 'AT1G06000',
 'AT1G06010',
 'AT1G06040',
 'AT1G06060',
 'AT1G06070',
 'AT1G06100',
 'AT1G06110',
 'AT1G06130',
 'AT1G06150',
 'AT1G06180',
 'AT1G06190',
 'AT1G06200',
 'AT1G06210',
 'AT1G06220',
 'AT1G06230',
 'AT1G06240',
 'AT1G06290',
 'AT1G06350',
 'AT1G06360',
 'AT1G06380',
 'AT1G06390',
 'AT1G06400',
 'AT1G06410',
 'AT1G06430',
 'AT1G06460',
 'AT1G06470',
 'AT1G06475',
 'AT1G06500',
 'AT1G06515',
 'AT1G06510',
 'AT1G06530',
 'AT1G06550',
 'AT1G06570',
 'AT1G06645',
 'AT1G06650',
 'AT1G06670',
 'AT1G06680',
 'AT1G06690',
 'AT1G06700',
 'AT1G06730',
 'AT1G06760',
 'AT1G06780',
 'AT1G06790',
 'AT1G06820',
 'AT1G06830',
 'AT1G06850',
 'AT1G06870',
 'AT1G06890',
 'AT1G06900',
 'AT1G06950',
 'AT1G06960',
 'AT1G07000',
 'AT1G07010',
 'AT1G07020',
 'AT1G07030',
 'AT1G07040',
 'AT1G07050',
 'AT1G07070',
 'AT1G07080',
 'AT1G07090',
 'AT1G07110',
 'AT1G07128',
 'AT1G07130',
 'AT1G07135',
 'AT1G07140',
 'AT1G07170',
 'AT1G07180',
 'AT1G07200',
 'AT1G07210',
 'AT1G07230',
 'AT1G07240',
 'AT1G07250',
 'AT1G07280',
 'AT1G07300',
 'AT1G07310',
 'AT1G07320',
 'AT1G07350',
 'AT1G07360',
 'AT1G07370',
 'AT1G07420',
 'AT1G07440',
 'AT1G07470',
 'AT1G07480',
 'AT1G07510',
 'AT1G07530',
 'AT1G07570',
 'AT1G07590',
 'AT1G07610',
 'AT1G07615',
 'AT1G07630',
 'AT1G07640',
 'AT1G07650',
 'AT1G07660',
 'AT1G07670',
 'AT1G07700',
 'AT1G07720',
 'AT1G07728',
 'AT1G07750',
 'AT1G07770',
 'AT1G07780',
 'AT1G07790',
 'AT1G07810',
 'AT1G07820',
 'AT1G07830',
 'AT1G07840',
 'AT1G07890',
 'AT1G07902',
 'AT1G07910',
 'AT1G07920',
 'AT1G07930',
 'AT1G07940',
 'AT1G07950',
 'AT1G07960',
 'AT1G07970',
 'AT1G07980',
 'AT1G07990',
 'AT1G08000',
 'AT1G08010',
 'AT1G08040',
 'AT1G08050',
 'AT1G08090',
 'AT1G08110',
 'AT1G08115',
 'AT1G08125',
 'AT1G08130',
 'AT1G08160',
 'AT1G08165',
 'AT1G08180',
 'AT1G08190',
 'AT1G08200',
 'AT1G08210',
 'AT1G08230',
 'AT1G08250',
 'AT1G08315',
 'AT1G08360',
 'AT1G08370',
 'AT1G08380',
 'AT1G08390',
 'AT1G08420',
 'AT1G08450',
 'AT1G08460',
 'AT1G08465',
 'AT1G08470',
 'AT1G08480',
 'AT1G08490',
 'AT1G08500',
 'AT1G08510',
 'AT1G08520',
 'AT1G08540',
 'AT1G08550',
 'AT1G08560',
 'AT1G08570',
 'AT1G08580',
 'AT1G08600',
 'AT1G08620',
 'AT1G08640',
 'AT1G08660',
 'AT1G08680',
 'AT1G08700',
 'AT1G08710',
 'AT1G08750',
 'AT1G08770',
 'AT1G08780',
 'AT1G08800',
 'AT1G08810',
 'AT1G08820',
 'AT1G08830',
 'AT1G08845',
 'AT1G08880',
 'AT1G08890',
 'AT1G08900',
 'AT1G08910',
 'AT1G08920',
 'AT1G08930',
 'AT1G08940',
 'AT1G08960',
 'AT1G08970',
 'AT1G08980',
 'AT1G09010',
 'AT1G09020',
 'AT1G09060',
 'AT1G09070',
 'AT1G09100',
 'AT1G09130',
 'AT1G09140',
 'AT1G09150',
 'AT1G09160',
 'AT1G09200',
 'AT1G09210',
 'AT1G09230',
 'AT1G09240',
 'AT1G09250',
 'AT1G09270',
 'AT1G09290',
 'AT1G09310',
 'AT1G09320',
 'AT1G09330',
 'AT1G09340',
 'AT1G09350',
 'AT1G09390',
 'AT1G09415',
 'AT1G09430',
 'AT1G09520',
 'AT1G09530',
 'AT1G09560',
 'AT1G09570',
 'AT1G09580',
 'AT1G09590',
 'AT1G09620',
 'AT1G09630',
 'AT1G09640',
 'AT1G09645',
 'AT1G09660',
 'AT1G09690',
 'AT1G09730',
 'AT1G09740',
 'AT1G09750',
 'AT1G09760',
 'AT1G09770',
 'AT1G09780',
 'AT1G09794',
 'AT1G09795',
 'AT1G09815',
 'AT1G09830',
 'AT1G09840',
 'AT1G09850',
 'AT1G09870',
 'AT1G09920',
 'AT1G09970',
 'AT1G09980',
 'AT1G10020',
 'AT1G10030',
 'AT1G10060',
 'AT1G10090',
 'AT1G10120',
 'AT1G10140',
 'AT1G10150',
 'AT1G10155',
 'AT1G10170',
 'AT1G10200',
 'AT1G10280',
 'AT1G10290',
 'AT1G10310',
 'AT1G10320',
 'AT1G10360',
 'AT1G10370',
 'AT1G10380',
 'AT1G10390',
 'AT1G10410',
 'AT1G10430',
 'AT1G10470',
 'AT1G10500',
 'AT1G10510',
 'AT1G10522',
 'AT1G10580',
 'AT1G10590',
 'AT1G10600',
 'AT1G10630',
 'AT1G10650',
 'AT1G10657',
 'AT1G10660',
 'AT1G10670',
 'AT1G10682',
 'AT1G10690',
 'AT1G10700',
 'AT1G10720',
 'AT1G10740',
 'AT1G10760',
 'AT1G10820',
 'AT1G10830',
 'AT1G10840',
 'AT1G10850',
 'AT1G10865',
 'AT1G10890',
 'AT1G10940',
 'AT1G10950',
 'AT1G10960',
 'AT1G11020',
 'AT1G11050',
 'AT1G11060',
 'AT1G11090',
 'AT1G11120',
 'AT1G11175',
 'AT1G11180',
 'AT1G11200',
 'AT1G11210',
 'AT1G11240',
 'AT1G11260',
 'AT1G11310',
 'AT1G11330',
 'AT1G11350',
 'AT1G11360',
 'AT1G11400',
 'AT1G11430',
 'AT1G11440',
 'AT1G11475',
 'AT1G11480',
 'AT1G11530',
 'AT1G11545',
 'AT1G11580',
 'AT1G11592',
 'AT1G11600',
 'AT1G11650',
 'AT1G11660',
 'AT1G11680',
 'AT1G11700',
 'AT1G11720',
 'AT1G11750',
 'AT1G11755',
 'AT1G11760',
 'AT1G11780',
 'AT1G11790',
 'AT1G11800',
 'AT1G11820',
 'AT1G11840',
 'AT1G11850',
 'AT1G11860',
 'AT1G11870',
 'AT1G04907',
 'AT1G11890',
 'AT1G11905',
 'AT1G11910',
 'AT1G11930',
 'AT1G12000',
 'AT1G12013',
 'AT1G12020',
 'AT1G12050',
 'AT1G12090',
 'AT1G12110',
 'AT1G12120',
 'AT1G12140',
 'AT1G12230',
 'AT1G12240',
 'AT1G12244',
 'AT1G12250',
 'AT1G12270',
 'AT1G12320',
 'AT1G12310',
 'AT1G12330',
 'AT1G12340',
 'AT1G12350',
 'AT1G12360',
 'AT1G12370',
 'AT1G12400',
 'AT1G12410',
 'AT1G12420',
 'AT1G12430',
 'AT1G12440',
 'AT1G12470',
 'AT1G12480',
 'AT1G12500',
 'AT1G12520',
 'AT1G12530',
 'AT1G12550',
 'AT1G12570',
 'AT1G12580',
 'AT1G12640',
 'AT1G12650',
 'AT1G12680',
 'AT1G12710',
 'AT1G12750',
 'AT1G12760',
 'AT1G12770',
 'AT1G12780',
 'AT1G12800',
 'AT1G12810',
 'AT1G12820',
 'AT1G12840',
 'AT1G12830',
 'AT1G12845',
 'AT1G12850',
 'AT1G12860',
 'AT1G12880',
 'AT1G12900',
 'AT1G12910',
 'AT1G12920',
 'AT1G12940',
 'AT1G12990',
 'AT1G13000',
 'AT1G13020',
 'AT1G13060',
 'AT1G13090',
 'AT1G13100',
 'AT1G13110',
 'AT1G13120',
 'AT1G13145',
 'AT1G13160',
 'AT1G13180',
 'AT1G13190',
 'AT1G13195',
 'AT1G13210',
 'AT1G13220',
 'AT1G13245',
 'AT1G13250',
 'AT1G13260',
 'AT1G13270',
 'AT1G13280',
 'AT1G13320',
 'AT1G13340',
 'AT1G13350',
 'AT1G13360',
 'AT1G13380',
 'AT1G13390',
 'AT1G13440',
 'AT1G13448',
 'AT1G13450',
 'AT1G13460',
 'AT1G13470',
 'AT1G13560',
 'AT1G13580',
 'AT1G13640',
 'AT1G13690',
 'AT1G13700',
 'AT1G13710',
 'AT1G13730',
 'AT1G13740',
 'AT1G13750',
 'AT1G13770',
 'AT1G13820',
 'AT1G13830',
 'AT1G13860',
 'AT1G13870',
 'AT1G13880',
 'AT1G13900',
 'AT1G13910',
 'AT1G13930',
 'AT1G13960',
 'AT1G13990',
 'AT1G14000',
 'AT1G14010',
 'AT1G14020',
 'AT1G14030',
 'AT1G14060',
 'AT1G14140',
 'AT1G14150',
 'AT1G14170',
 'AT1G14200',
 'AT1G14210',
 'AT1G14230',
 'AT1G14270',
 'AT1G14280',
 'AT1G14290',
 'AT1G14300',
 'AT1G14310',
 'AT1G14320',
 'AT1G14330',
 'AT1G14340',
 'AT1G14345',
 'AT1G14350',
 'AT1G14360',
 'AT1G14370',
 'AT1G14380',
 'AT1G14400',
 'AT1G14410',
 'AT1G14430',
 'AT1G14450',
 'AT1G14510',
 'AT1G14570',
 'AT1G14580',
 'AT1G14610',
 'AT1G14630',
 'AT1G14650',
 'AT1G14670',
 'AT1G14685',
 'AT1G14690',
 'AT1G14700',
 'AT1G14710',
 'AT1G14720',
 'AT1G14740',
 'AT1G14810',
 'AT1G14820',
 'AT1G14830',
 'AT1G14840',
 'AT1G14850',
 'AT1G14870',
 'AT1G14880',
 'AT1G14890',
 'AT1G14900',
 'AT1G14910',
 'AT1G14920',
 'AT1G14980',
 'AT1G14990',
 'AT1G15000',
 'AT1G15030',
 'AT1G15060',
 'AT1G05153',
 'AT1G15085',
 'AT1G15100',
 'AT1G15120',
 'AT1G15130',
 'AT1G15140',
 'AT1G15170',
 'AT1G15180',
 'AT1G15200',
 'AT1G15230',
 'AT1G15240',
 'AT1G15250',
 'AT1G15260',
 'AT1G15270',
 'AT1G15280',
 'AT1G15290',
 'AT1G15340',
 'AT1G15350',
 'AT1G15370',
 'AT1G15390',
 'AT1G15400',
 'AT1G15410',
 'AT1G15420',
 'AT1G15430',
 'AT1G15440',
 'AT1G15470',
 'AT1G15500',
 'AT1G15550',
 'AT1G15660',
 'AT1G15670',
 'AT1G15690',
 'AT1G15710',
 'AT1G15730',
 'AT1G15740',
 'AT1G15750',
 'AT1G15810',
 'AT1G15820',
 'AT1G15860',
 'AT1G15870',
 'AT1G15880',
 'AT1G15910',
 'AT1G15920',
 'AT1G15930',
 'AT1G15940',
 'AT1G15950',
 'AT1G15970',
 'AT1G15980',
 'AT1G16000',
 'AT1G16010',
 'AT1G16040',
 'AT1G16060',
 'AT1G16080',
 'AT1G16170',
 'AT1G16180',
 'AT1G16190',
 'AT1G16210',
 'AT1G16240',
 'AT1G16250',
 'AT1G16320',
 'AT1G16340',
 'AT1G16350',
 'AT1G16390',
 'AT1G16400',
 'AT1G16410',
 'AT1G16430',
 'AT1G16445',
 'AT1G16460',
 'AT1G16470',
 'AT1G16500',
 'AT1G16510',
 'AT1G16515',
 'AT1G16520',
 'AT1G16560',
 'AT1G16570',
 'AT1G16610',
 'AT1G16640',
 'AT1G16670',
 'AT1G16680',
 'AT1G16700',
 'AT1G16710',
 'AT1G16720',
 'AT1G16730',
 'AT1G16740',
 'AT1G16750',
 'AT1G16790',
 'AT1G16810',
 'AT1G05273',
 'AT1G16825',
 'AT1G16840',
 'AT1G16850',
 'AT1G16860',
 'AT1G16870',
 'AT1G16880',
 'AT1G16890',
 'AT1G16900',
 'AT1G16916',
 'AT1G16920',
 'AT1G16960',
 'AT1G17050',
 'AT1G17070',
 'AT1G17080',
 'AT1G17100',
 'AT1G17110',
 'AT1G17120',
 'AT1G17130',
 'AT1G17140',
 'AT1G17145',
 'AT1G17160',
 'AT1G17170',
 'AT1G17190',
 'AT1G17200',
 'AT1G17210',
 'AT1G17220',
 'AT1G17280',
 'AT1G17290',
 'AT1G17330',
 'AT1G17340',
 'AT1G17350',
 'AT1G17360',
 'AT1G17370',
 'AT1G17410',
 'AT1G17420',
 'AT1G17430',
 'AT1G17440',
 'AT1G17455',
 'AT1G17470',
 'AT1G17490',
 'AT1G17500',
 'AT1G17510',
 'AT1G17530',
 'AT1G17550',
 'AT1G17560',
 'AT1G17620',
 'AT1G17650',
 'AT1G17665',
 'AT1G17690',
 'AT1G17720',
 'AT1G17730',
 'AT1G17745',
 'AT1G17780',
 'AT1G17840',
 'AT1G17860',
 'AT1G17880',
 'AT1G17890',
 'AT1G17970',
 'AT1G17980',
 'AT1G18030',
 'AT1G18060',
 'AT1G18070',
 'AT1G18075',
 'AT1G18080',
 'AT1G18150',
 'AT1G18160',
 'AT1G18170',
 'AT1G18190',
 'AT1G18210',
 'AT1G18250',
 'AT1G18260',
 'AT1G18270',
 'AT1G18340',
 'AT1G18360',
 'AT1G18400',
 'AT1G18440',
 'AT1G18450',
 'AT1G18460',
 'AT1G18470',
 'AT1G18480',
 'AT1G18490',
 'AT1G18500',
 'AT1G18540',
 'AT1G18590',
 'AT1G18600',
 'AT1G18620',
 'AT1G18630',
 'AT1G18640',
 'AT1G18650',
 'AT1G18660',
 'AT1G18680',
 'AT1G18700',
 'AT1G18710',
 'AT1G18720',
 'AT1G18730',
 'AT1G18740',
 'AT1G18800',
 'AT1G18810',
 'AT1G18840',
 'AT1G18850',
 'AT1G18890',
 'AT1G18900',
 'AT1G18950',
 'AT1G19000',
 'AT1G19020',
 'AT1G19050',
 'AT1G19080',
 'AT1G19100',
 'AT1G19110',
 'AT1G19120',
 'AT1G19130',
 'AT1G19140',
 'AT1G19150',
 'AT1G19170',
 'AT1G19180',
 'AT1G19200',
 'AT1G19240',
 'AT1G19270',
 'AT1G19300',
 'AT1G19310',
 'AT1G19330',
 'AT1G19350',
 'AT1G19360',
 'AT1G19370',
 'AT1G19380',
 'AT1G19400',
 'AT1G19430',
 'AT1G19440',
 'AT1G19450',
 'AT1G19480',
 'AT1G19510',
 'AT1G19520',
 'AT1G19570',
 'AT1G19580',
 'AT1G19600',
 'AT1G19610',
 'AT1G19660',
 'AT1G19670',
 'AT1G19680',
 'AT1G19690',
 'AT1G19700',
 'AT1G19715',
 'AT1G19720',
 'AT1G19730',
 'AT1G19740',
 'AT1G19770',
 'AT1G19800',
 'AT1G19835',
 'AT1G19840',
 'AT1G19870',
 'AT1G19880',
 'AT1G19910',
 'AT1G19920',
 'AT1G19950',
 'AT1G19960',
 'AT1G19970',
 'AT1G19990',
 'AT1G20010',
 'AT1G20015',
 'AT1G20020',
 'AT1G20050',
 'AT1G20070',
 'AT1G20090',
 'AT1G20100',
 'AT1G20110',
 'AT1G20140',
 'AT1G20190',
 ...]

In [13]:
filtered_circadian_1

,test,period,p,q,amplitude,p(amplitude),q(amplitude),CI(amplitude),acrophase,p(acrophase),q(acrophase),CI(acrophase),acrophase[h]
0,AT1G01020,24.0,2.102497e-02,5.078886e-02,0.918085,4.710387e-03,1.136635e-02,"[np.float64(0.2813949244319637), np.float64(1....",-1.169566,1.142287e-03,3.312285e-03,"[np.float64(-1.8742590565617578), np.float64(-...",4.467411
1,AT1G01030,24.0,1.022071e-01,1.755511e-01,0.386880,3.113175e-02,5.341614e-02,"[np.float64(0.03507695668373073), np.float64(0...",-2.801896,1.101758e-09,7.607475e-09,"[np.float64(-3.703057726194051), np.float64(-1...",10.702452
2,AT1G01040,24.0,2.707276e-01,3.724769e-01,0.316121,1.038610e-01,1.429474e-01,"[np.float64(-0.06483027596836577), np.float64(...",-0.646499,3.203545e-01,4.398152e-01,"[np.float64(-1.921608941659519), np.float64(0....",2.469444
3,AT1G01050,24.0,5.989641e-01,6.764105e-01,1.435231,3.101725e-01,3.503685e-01,"[np.float64(-1.336579953849928), np.float64(4....",0.946954,3.089308e-01,4.279015e-01,"[np.float64(-0.8771777739292927), np.float64(2...",20.382901
4,AT1G01060,24.0,1.079806e-22,3.717545e-20,10.427311,1.313264e-38,4.521291e-36,"[np.float64(8.854566775117929), np.float64(12....",3.130199,0.000000e+00,0.000000e+00,"[np.float64(2.974739132189778), np.float64(3.2...",12.043522
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14797,ArthCr090,24.0,3.009902e-01,4.034537e-01,4.931478,1.197321e-01,1.604521e-01,"[np.float64(-1.2806988632203913), np.float64(1...",-2.972522,4.748691e-06,2.065206e-05,"[np.float64(-4.245807128919859), np.float64(-1...",11.354198
14798,ArthCr089,24.0,6.659340e-01,7.318303e-01,12.072629,3.669820e-01,4.032961e-01,"[np.float64(-14.155999378226738), np.float64(3...",-3.065889,6.769886e-03,1.654911e-02,"[np.float64(-5.284917819183006), np.float64(-0...",11.710835
14801,ArthCr088,24.0,5.301851e-01,6.166125e-01,0.384770,2.593235e-01,3.015494e-01,"[np.float64(-0.2837949765125131), np.float64(1...",-2.883700,1.148742e-03,3.326027e-03,"[np.float64(-4.622059771966897), np.float64(-1...",11.014923
14802,ArthCp088,24.0,9.359798e-02,1.641930e-01,0.981437,2.798974e-02,4.904831e-02,"[np.float64(0.10605937085861394), np.float64(1...",-2.926267,1.598744e-10,1.194741e-09,"[np.float64(-3.8230310076464984), np.float64(-...",11.177518
14803,ArthCp085,24.0,8.274965e-01,8.638500e-01,0.199468,5.379446e-01,5.616172e-01,"[np.float64(-0.43526984454730633), np.float64(...",-0.578823,7.365235e-01,8.156623e-01,"[np.float64(-3.9506074419551784), np.float64(2...",2.210942

In [94]:
p_value_cutoff = 4e-9

##Sugar transporter activity at 4e-9 + >50 samples over 1 expression (14187 rows)

In [95]:
fully_circadian_genes_1 = filtered_circadian_1[
    (filtered_circadian_1["p"] < p_value_cutoff)
]
fully_circadian_genes_1

,test,period,p,q,amplitude,p(amplitude),q(amplitude),CI(amplitude),acrophase,p(acrophase),q(acrophase),CI(acrophase),acrophase[h]
4,AT1G01060,24.0,1.079806e-22,3.717545e-20,10.427311,1.313264e-38,4.521291e-36,"[np.float64(8.854566775117929), np.float64(12....",3.130199,0.000000e+00,0.000000e+00,"[np.float64(2.974739132189778), np.float64(3.2...",12.043522
20,AT1G01250,24.0,2.435015e-10,6.357665e-09,18.724029,1.243262e-13,3.246077e-12,"[np.float64(13.77287025342332), np.float64(23....",1.172994,3.619396e-20,5.103004e-19,"[np.float64(0.923067297477144), np.float64(1.4...",19.519494
23,AT1G01300,24.0,1.124310e-10,3.116907e-09,3.875622,3.966200e-14,1.097488e-12,"[np.float64(2.871128501982337), np.float64(4.8...",0.570049,8.261861e-06,3.478629e-05,"[np.float64(0.3194423578869212), np.float64(0....",21.822573
35,AT1G01500,24.0,1.871338e-10,4.957412e-09,2.633123,9.048791e-14,2.396392e-12,"[np.float64(1.9407752620448608), np.float64(3....",1.832763,1.728224e-42,5.610663e-41,"[np.float64(1.5698198331592668), np.float64(2....",16.999361
37,AT1G01540,24.0,1.407616e-10,3.830579e-09,2.903909,5.564880e-14,1.514384e-12,"[np.float64(2.1468451825578985), np.float64(3....",-0.937935,1.207313e-11,9.973805e-11,"[np.float64(-1.2090999613188762), np.float64(-...",3.582647
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14644,AT5G67140,24.0,4.093233e-12,1.582147e-10,6.671338,1.913349e-16,7.414979e-15,"[np.float64(5.082063499231786), np.float64(8.2...",3.109481,1.865082e-135,2.733730e-133,"[np.float64(2.863443580992479), np.float64(3.3...",12.122657
14664,AT5G67385,24.0,2.403240e-11,7.785026e-10,2.385340,3.357690e-15,1.094873e-13,"[np.float64(1.7918052018061865), np.float64(2....",-1.727928,7.678741e-46,2.739183e-44,"[np.float64(-1.9662184977236468), np.float64(-...",6.600198
14665,AT5G67390,24.0,9.027708e-11,2.535981e-09,2.010859,2.804795e-14,7.878972e-13,"[np.float64(1.4927575452190809), np.float64(2....",2.155256,1.898024e-56,8.916881e-55,"[np.float64(1.8884252285964775), np.float64(2....",15.767530
14670,AT5G67490,24.0,1.115844e-10,3.099241e-09,27.426041,3.680645e-14,1.024216e-12,"[np.float64(20.326805480209753), np.float64(34...",-0.438341,1.724966e-03,4.790170e-03,"[np.float64(-0.7124820158249852), np.float64(-...",1.674339
14748,ArthCp031,24.0,2.692568e-09,5.490464e-08,199.764137,5.084567e-12,1.033955e-10,"[np.float64(143.04684866680793), np.float64(25...",-2.863769,2.640465e-87,2.112943e-85,"[np.float64(-3.1471612973242586), np.float64(-...",10.938791

In [96]:
fully_circadian_genes_2 = filtered_circadian_2[
    (filtered_circadian_2["p"] < p_value_cutoff)
]
fully_circadian_genes_2

,test,period,p,q,amplitude,p(amplitude),q(amplitude),CI(amplitude),acrophase,p(acrophase),q(acrophase),CI(acrophase),acrophase[h]
4,AT1G01060,24.0,9.607864e-16,4.190775e-13,6.437807,2.438295e-23,1.063540e-20,"[np.float64(5.170106632863515), np.float64(7.7...",-2.765351,1.903328e-150,1.141521e-147,"[np.float64(-2.972815722700038), np.float64(-2...",10.562862
306,AT1G06040,24.0,1.423077e-15,5.852508e-13,41.664809,4.745636e-23,1.951677e-20,"[np.float64(33.405228531847314), np.float64(49...",-3.097189,7.595837e-179,7.288965e-176,"[np.float64(-3.310071056870583), np.float64(-2...",11.830389
331,AT1G06460,24.0,2.762475e-14,8.460226e-12,37.487030,1.458976e-20,4.468191e-18,"[np.float64(29.58324097781501), np.float64(45....",1.529763,1.180905e-52,1.096642e-50,"[np.float64(1.3334332079088418), np.float64(1....",18.156737
370,AT1G07050,24.0,9.687183e-15,3.319936e-12,23.436079,2.057803e-21,7.052386e-19,"[np.float64(18.601982768894928), np.float64(28...",1.389578,2.974325e-45,2.241489e-43,"[np.float64(1.1966561279689958), np.float64(1....",18.692203
381,AT1G07180,24.0,1.827005e-12,4.241599e-10,11.504653,2.862019e-17,6.644500e-15,"[np.float64(8.836818389040538), np.float64(14....",-2.948552,2.567039e-120,9.237491e-118,"[np.float64(-3.196331142061808), np.float64(-2...",11.262638
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13649,AT5G57380,24.0,1.210390e-09,1.382727e-07,2.644176,1.179654e-12,1.347614e-10,"[np.float64(1.9150416708442457), np.float64(3....",2.001679,3.048908e-50,2.612261e-48,"[np.float64(1.7384678605789117), np.float64(2....",16.354148
13923,AT5G62360,24.0,2.783050e-10,3.709187e-08,54.319572,1.198962e-13,1.597950e-11,"[np.float64(39.96526669690087), np.float64(68....",1.958948,8.960228e-53,8.429642e-51,"[np.float64(1.7078329403635544), np.float64(2....",16.517370
13926,AT5G62430,24.0,1.094641e-13,2.917828e-11,13.954386,2.059244e-19,5.592596e-17,"[np.float64(10.918883405694856), np.float64(16...",-1.948135,2.428693e-76,4.369825e-74,"[np.float64(-2.1546256790963025), np.float64(-...",7.441327
14096,AT5G64840,24.0,6.270628e-12,1.271259e-09,13.246314,2.492260e-16,5.052619e-14,"[np.float64(10.078502408244491), np.float64(16...",-2.767591,9.260118e-103,2.720207e-100,"[np.float64(-3.019605164397587), np.float64(-2...",10.571419
14104,AT5G64940,24.0,3.717202e-14,1.103685e-11,15.703629,2.995858e-20,8.983828e-18,"[np.float64(12.365068461016895), np.float64(19...",-2.617446,6.270499e-120,2.201404e-117,"[np.float64(-2.8377619664148983), np.float64(-...",9.997906

In [97]:
circadian_1_gene_list_large = fully_circadian_genes_1["test"].tolist()
circadian_2_gene_list_large = fully_circadian_genes_2["test"].tolist()

In [98]:
background_genes_list = list(background_genes)

In [99]:
if "go_term_matrix" not in globals():
    go_term_matrix = pd.read_csv(
        "/Users/michael/Data/Reference_data/Arabdidopsis_go_matrix_from_tair_gaf.csv",
        index_col=0,
    )

if "go_term_names" not in globals():
    go_term_names = pd.read_csv(
        "/Users/michael/Data/Reference_data/goterm_names.csv", index_col=0
    )

In [100]:
def run_go_term_analysis(gene_list, background_genes, go_term_matrix, go_term_names):
    cont_tables_large = Go_tools.generate_contigency_tables(
        go_annotations=go_term_matrix,
        gene_list=gene_list,
        use_background_genes=True,
        background_genes=background_genes,
    )

    fishers_results_large = Go_tools.fishers_exact_on_contigency_tables(
        all_go_contigency_tables=cont_tables_large,
        original_GO_term_panda=go_term_matrix,
    )
    corrected_fishers_results_large = Go_tools.multi_hypothesis_correct_fishers_exact(
        fishers_results_large
    )
    named_large_fishers_results = corrected_fishers_results_large.merge(
        go_term_names, left_index=True, right_index=True, how="left"
    )
    return named_large_fishers_results

In [101]:
cont_tables_large = Go_tools.generate_contigency_tables(
    go_annotations=go_term_matrix,
    gene_list=circadian_1_gene_list_large,
    use_background_genes=True,
    background_genes=background_genes_list,
)

fishers_results_large = Go_tools.fishers_exact_on_contigency_tables(
    all_go_contigency_tables=cont_tables_large,
    original_GO_term_panda=go_term_matrix,
)

corrected_fishers_results_large = Go_tools.multi_hypothesis_correct_fishers_exact(
    fishers_results_large
)

named_large_fishers_results = corrected_fishers_results_large.merge(
    go_term_names, left_index=True, right_index=True, how="left"
)
named_large_fishers_results.sort_values("P_value").head(40)

/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:49: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  - go_subset_distribution_num_genes_annotatated_with_go_term[i]
/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  go_subset_distribution_num_genes_annotatated_with_go_term[i],
/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:55: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  background_dipstribution_num_genes_that_lack_go_term[i]
/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:56: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  - go_subset_distribution_num_genes_that_lack_go_term[i]
/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:58: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  go_subset_distribution_num_genes_that_lack_go_term[i],

                 P_value                                                  x
GO:0007623  1.012046e-13                                   circadian rhythm
GO:0009409  1.527835e-10                                   response to cold
GO:0016168  2.506022e-06                                chlorophyll binding
GO:0009769  2.086608e-05  photosynthesis, light harvesting in photosyste...
GO:0009644  2.086608e-05                   response to high light intensity
GO:0010114  2.746459e-05                              response to red light
GO:0009414  8.803914e-05                      response to water deprivation
GO:0042752  8.803914e-05                     regulation of circadian rhythm
GO:0006355  8.803914e-05          regulation of DNA-templated transcription
GO:0009416  4.189815e-04                         response to light stimulus
GO:0003700  8.953899e-04          DNA-binding transcription factor activity
GO:0038023  1.529456e-03                        signaling receptor activity
GO:0010427  2.971762e-03                              abscisic acid binding
GO:0005576  3.760597e-03                               extracellular region
GO:0009505  4.620638e-03                               plant-type cell wall
GO:0004864  4.620638e-03             protein phosphatase inhibitor activity
GO:0009523  1.082048e-02                                     photosystem II
GO:0000293  1.082048e-02                  ferric-chelate reductase activity
GO:0009637  2.021494e-02                             response to blue light
GO:0009645  2.021494e-02           response to low light intensity stimulus
GO:0009768  2.021494e-02  photosynthesis, light harvesting in photosystem I
GO:1903428  3.475680e-02  positive regulation of reactive oxygen species...
GO:0042819  3.475680e-02                    vitamin B6 biosynthetic process
GO:0008270  4.204112e-02                                   zinc ion binding
GO:0009517  4.827875e-02        PSII associated light-harvesting complex II
GO:0051119  4.827875e-02           sugar transmembrane transporter activity
GO:0009579  5.406654e-02                                          thylakoid
GO:0010287  5.443989e-02                                      plastoglobule
GO:0010218  6.565646e-02                          response to far red light
GO:0010378  8.313031e-02    temperature compensation of the circadian clock
GO:0050658  8.313031e-02                                      RNA transport
GO:0140110  8.313031e-02                   transcription regulator activity
GO:0006858  8.313031e-02                            extracellular transport
GO:0006857  8.313031e-02                             oligopeptide transport
GO:0006970  8.313031e-02                         response to osmotic stress
GO:0004506  8.313031e-02                    squalene monooxygenase activity
GO:0009750  8.313031e-02                               response to fructose
GO:0009649  1.095187e-01                     entrainment of circadian clock
GO:0009534  1.224499e-01                              chloroplast thylakoid
GO:0009651  1.290936e-01                            response to salt stress

In [93]:
cont_tables_large_2 = Go_tools.generate_contigency_tables(
    go_annotations=go_term_matrix,
    gene_list=circadian_2_gene_list_large,
    use_background_genes=True,
    background_genes=background_genes_list,
)

fishers_results_large_2 = Go_tools.fishers_exact_on_contigency_tables(
    all_go_contigency_tables=cont_tables_large_2,
    original_GO_term_panda=go_term_matrix,
)

corrected_fishers_results_large_2 = Go_tools.multi_hypothesis_correct_fishers_exact(
    fishers_results_large_2
)

named_large_fishers_results_2 = corrected_fishers_results_large_2.merge(
    go_term_names, left_index=True, right_index=True, how="left"
)
named_large_fishers_results_2.sort_values("P_value").head(40)

/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:49: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  - go_subset_distribution_num_genes_annotatated_with_go_term[i]
/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  go_subset_distribution_num_genes_annotatated_with_go_term[i],
/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:55: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  background_dipstribution_num_genes_that_lack_go_term[i]
/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:56: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  - go_subset_distribution_num_genes_that_lack_go_term[i]
/Users/michael/Git/Bioinformatics_utils/Utilities/Go_tools.py:58: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  go_subset_distribution_num_genes_that_lack_go_term[i],

                 P_value                                                  x
GO:0007623  3.369097e-11                                   circadian rhythm
GO:0016168  2.278469e-08                                chlorophyll binding
GO:0009769  2.372947e-07  photosynthesis, light harvesting in photosyste...
GO:0006355  6.881550e-05          regulation of DNA-templated transcription
GO:0009644  1.494600e-04                   response to high light intensity
GO:0009645  1.063857e-03           response to low light intensity stimulus
GO:0009768  1.063857e-03  photosynthesis, light harvesting in photosystem I
GO:0010114  1.462825e-03                              response to red light
GO:0042651  1.770707e-03                                 thylakoid membrane
GO:0009409  1.902312e-03                                   response to cold
GO:0003700  2.031437e-03          DNA-binding transcription factor activity
GO:0009517  4.067399e-03        PSII associated light-harvesting complex II
GO:0009579  4.959756e-03                                          thylakoid
GO:1903428  4.959756e-03  positive regulation of reactive oxygen species...
GO:0015995  9.449648e-03                   chlorophyll biosynthetic process
GO:0009535  1.490790e-02                     chloroplast thylakoid membrane
GO:0008270  1.492989e-02                                   zinc ion binding
GO:0042752  1.492989e-02                     regulation of circadian rhythm
GO:0009534  1.826719e-02                              chloroplast thylakoid
GO:0009416  2.277727e-02                         response to light stimulus
GO:0009523  2.925870e-02                                     photosystem II
GO:0009522  2.925870e-02                                      photosystem I
GO:0015706  6.884120e-02                    nitrate transmembrane transport
GO:0010100  6.884120e-02          negative regulation of photomorphogenesis
GO:0042754  1.112015e-01            negative regulation of circadian rhythm
GO:0019904  1.112015e-01                    protein domain specific binding
GO:0001173  1.112015e-01  DNA-templated transcriptional start site selec...
GO:0010600  1.170997e-01           regulation of auxin biosynthetic process
GO:0005515  1.170997e-01                                    protein binding
GO:0000156  1.170997e-01           phosphorelay response regulator activity
GO:0019853  1.631812e-01               L-ascorbic acid biosynthetic process
GO:0010287  1.907949e-01                                      plastoglobule
GO:0006094  2.153816e-01                                    gluconeogenesis
GO:0010017  2.603934e-01             red or far-red light signaling pathway
GO:0003677  2.603934e-01                                        DNA binding
GO:0047274  2.603934e-01  galactinol-sucrose galactosyltransferase activity
GO:0009414  2.886703e-01                      response to water deprivation
GO:0015140  4.371652e-01          malate transmembrane transporter activity
GO:0010325  4.371652e-01  raffinose family oligosaccharide biosynthetic ...
GO:0010218  4.371652e-01                          response to far red light

In [ ]:
filtered_circadian_1_aligned = filtered_circadian_1.set_index("test")
filtered_circadian_2_aligned = filtered_circadian_2.set_index("test")
filtered_circadian_1_aligned

In [ ]:
### Smaller is better so if answer is positive then experiment 2 is better, if negative then experiment 1 is better.
### The biggest gain possible is 1
circadian_delta_p = (
    filtered_circadian_1_aligned["p"] - filtered_circadian_2_aligned["p"]
)
circadian_delta_p = circadian_delta_p.to_frame(name="delta_p")
circadian_delta_p = circadian_delta_p.sort_values("delta_p", ascending=False)
circadian_delta_p

In [ ]:
genes_that_become_more_circadian_in_experiment_2 = circadian_delta_p[
    0:80
].index.to_list()
genes_that_become_more_circadian_in_experiment_1 = circadian_delta_p[
    -80:
].index.to_list()

In [ ]:
run_go_term_analysis(
    gene_list=genes_that_become_more_circadian_in_experiment_2,
    background_genes=background_genes_list,
    go_term_matrix=go_term_matrix,
    go_term_names=go_term_names,
).sort_values("P_value").head(40)

In [ ]:
run_go_term_analysis(
    gene_list=genes_that_become_more_circadian_in_experiment_1,
    background_genes=background_genes_list,
    go_term_matrix=go_term_matrix,
    go_term_names=go_term_names,
).sort_values("P_value").head(40)