In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
core_results = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/Generated_data/species_core_results.csv"
)
core_results.loc[core_results["core"] == True,]

,Species,n_samples_present,mean_abundance_present,median_abundance_present,prevalence,core
0,Kordiimonas sp002401685,372,3.661053,3.30,1.000000,True
1,Sphingomonas_L_486704 sp000786205,372,17.954211,15.90,1.000000,True
2,Rhodoferax_C aquaticus,370,4.407143,3.70,0.994624,True
3,Neorhizobium soli,366,3.855080,2.25,0.983871,True
4,Klenkia sp001424455,363,3.581402,2.70,0.975806,True
5,Massilia atriviolacea,353,5.457064,3.10,0.948925,True
6,Variovorax paradoxus_C,340,2.968391,2.35,0.913978,True
7,Flavobacterium chilense,328,8.458333,4.80,0.881720,True
8,Sphingomonas_L_486704 taxi,319,1.840557,1.40,0.857527,True
9,Frigoribacterium sp001424645,298,2.820328,1.50,0.801075,True

In [ ]:
####Kordiimonas - not there, not real? Why is it present in 100 percent samples
## Sphingomonas - present in hub
## Rhodoferax - not in hub
## Neorhizobium - present in hub
## Klenkia - not in hub
## Massillia - present in hub
## Variovorax - present in hub
## Flavobacterium - not in hub
### Frigoribacterium - Not in hub

In [3]:
hub_genes_brachi = pd.read_csv(
    "/Users/michael/Data/Luke_terrace_experiment/General_data/hub_info_brachi_paper.csv",
    sep="\t",
)
hub_genes_brachi = hub_genes_brachi.loc[
    (hub_genes_brachi["hub"] > 0) & (hub_genes_brachi["domain"] == "Bacteria")
]
hub_genes_brachi

,OTU,heritable,hub,heritable hub,Nexp,Core microbiota,% match in field isolates,domain,phyla,class,order,family,genus,species
0,B1,2,2,0,8,1,100,Bacteria,Proteobacteria,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae,Sphingomonas,NaN
4,B102,0,1,0,5,0,0,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Devosiaceae,Devosia,NaN
10,B107,1,1,1,5,0,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,[Aquaspirillum] arcticum group,uncultured bacterium
15,B111,1,1,0,8,1,99,Bacteria,Proteobacteria,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae,Sphingomonas,NaN
20,B116,0,1,0,5,0,0,Bacteria,Actinobacteria,Actinobacteria,Propionibacteriales,Nocardioidaceae,Marmoricola,NaN
23,B118,0,1,0,7,0,100,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Xanthobacteraceae,Tardiphaga,iron-reducing bacterium enrichment culture clo...
25,B12,5,3,1,8,1,100,Bacteria,Proteobacteria,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae,Sphingomonas,Sphingomonas aquatilis
36,B13,4,1,1,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,NaN,NaN
46,B139,0,2,0,5,0,0,Bacteria,Actinobacteria,Actinobacteria,Propionibacteriales,Nocardioidaceae,Nocardioides,NaN
56,B148,0,3,0,0,0,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,NaN,NaN
67,B158,0,1,0,3,0,0,Bacteria,Proteobacteria,Alphaproteobacteria,Acetobacterales,Acetobacteraceae,Roseomonas,Ambiguous taxa
91,B18,1,2,0,8,1,100,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Rhizobiaceae,Allorhizobium-Neorhizobium-Pararhizobium-Rhizo...,NaN
101,B189,2,1,0,2,0,0,Bacteria,Actinobacteria,Actinobacteria,Propionibacteriales,Nocardioidaceae,Nocardioides,uncultured bacterium
148,B230,0,1,0,3,0,0,Bacteria,Proteobacteria,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae,Rhizorhapis,Ambiguous taxa
163,B244,0,1,0,3,0,0,Bacteria,Actinobacteria,Actinobacteria,Frankiales,uncultured,NaN,NaN
169,B25,3,5,2,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,NaN,NaN
180,B26,4,5,3,8,1,98,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Beijerinckiaceae,Methylobacterium,uncultured bacterium
183,B262,0,1,0,2,0,0,Bacteria,Actinobacteria,Actinobacteria,Propionibacteriales,Nocardioidaceae,Nocardioides,NaN
202,B28,1,3,1,8,1,100,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,Polaromonas,NaN
213,B29,1,2,0,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,Massilia,NaN
224,B3,3,2,0,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,Janthinobacterium,NaN
291,B36,1,1,0,8,1,0,Bacteria,Proteobacteria,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae,Sphingomonas,Sphingomonas sp. FW-11
312,B38,2,1,1,8,1,100,Bacteria,Proteobacteria,Alphaproteobacteria,Caulobacterales,Caulobacteraceae,Brevundimonas,Ambiguous taxa
322,B39,2,2,0,8,1,100,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Beijerinckiaceae,Methylobacterium,Ambiguous taxa
326,B393,0,1,0,0,0,0,Bacteria,Actinobacteria,Actinobacteria,Frankiales,uncultured,Ambiguous taxa,NaN
332,B40,2,2,0,8,1,99,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Xanthobacteraceae,Tardiphaga,iron-reducing bacterium enrichment culture clo...
343,B41,2,6,2,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,NaN,NaN
396,B462,0,1,0,0,0,0,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Xanthobacteraceae,Bradyrhizobium,NaN
426,B5,3,4,1,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,Variovorax,NaN
443,B53,3,1,1,8,1,100,Bacteria,Proteobacteria,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae,Sphingomonas,uncultured soil bacterium
476,B58,2,1,0,8,1,100,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Beijerinckiaceae,Methylobacterium,Ambiguous taxa
502,B63,1,1,0,7,0,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Methylophilaceae,Methylotenera,NaN
527,B69,2,1,0,4,0,0,Bacteria,Actinobacteria,Actinobacteria,Micrococcales,Microbacteriaceae,Cryobacterium,Ambiguous taxa
530,B70,1,1,0,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,NaN,NaN
532,B71,3,1,0,8,1,0,Bacteria,Proteobacteria,Deltaproteobacteria,Myxococcales,Polyangiaceae,Aetherobacter,Ambiguous taxa
544,B75,0,2,0,8,1,0,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Beijerinckiaceae,Bosea,Ambiguous taxa
547,B76,4,2,1,8,1,0,Bacteria,Actinobacteria,Actinobacteria,Corynebacteriales,Nocardiaceae,Nocardia,actinobacterium P23
550,B78,0,2,0,7,0,100,Bacteria,Proteobacteria,Alphaproteobacteria,Rhizobiales,Devosiaceae,Devosia,uncultured bacterium
564,B84,2,1,0,4,0,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,NaN,NaN
569,B89,1,2,0,7,0,0,Bacteria,Actinobacteria,Actinobacteria,Propionibacteriales,Nocardioidaceae,Marmoricola,NaN
575,B94,0,1,0,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,NaN,NaN
579,B98,0,1,0,0,0,0,Bacteria,Proteobacteria,Gammaproteobacteria,Enterobacteriales,Enterobacteriaceae,Escherichia-Shigella,NaN
580,B99,1,1,1,8,1,0,Bacteria,Proteobacteria,Gammaproteobacteria,Betaproteobacteriales,Burkholderiaceae,Rhizobacter,Ambiguous taxa